version: '3'

networks:
  sde:
    external: true

services:
  process-centric:
    build: ./process-centric
    ports:
      - 8000:8000
    restart: on-failure
    env_file:
      - process-centric/src/.env
    networks:
      - sde
  db:
    build: ./db
    ports:
      - 8001:8000
    restart: on-failure
    env_file:
      - db/src/.env
    networks:
      - sde
  business-logic:
    build: ./business-logic
    ports:
      - 8002:8000
    restart: on-failure
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/firebase_key.json
    env_file:
      - business-logic/src/.env
    networks:
      - sde