version: '3'

services:
  process-centric:
    build: ./process-centric
    ports:
      - 8000:8000
  db:
    build: ./db
    ports:
      - 8001:8000
  business-logic:
    build: ./business-logic
    ports:
      - 8002:8000